Update pre-master-binding-k3s.yml

diff --git a/.github/workflows/pre-master-binding-k3s.yml b/.github/workflows/pre-master-binding-k3s.yml
--- a/.github/workflows/pre-master-binding-k3s.yml
+++ b/.github/workflows/pre-master-binding-k3s.yml
@@ -12,14 +12,6 @@ defaults:
     working-directory: components/binding
 
 jobs:
-  stub-to-be-updated:
-    runs-on: ubuntu-latest
-    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
-    steps:
-
-    - name: Branch based PR checkout
-      uses: actions/checkout@v2
-      
   pre-master-binding-k3s:
     env:
       PR_NUMBER: ${{ github.event.number }}
@@ -40,18 +32,18 @@ jobs:
       with:
         ref: 'refs/pull/${{ github.event.client_payload.pull_request.number }}/merge'
 
-   # - name: Go test, vet, fmt
-   #   run:  |
-   #     go test ./...
-   #     if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
-   #       echo "Some files are not properly formatted"
-   #       exit 1
-   #     fi
-   #     goVetResult=$(go vet ./...)
-   #     if [ $(echo ${#goVetResult}) != 0 ]; then
-   #         echo -e "go vet errors \n$goVetResult"
-   #         exit 1
-   #     fi
+    - name: Go test, vet, fmt
+      run:  |
+        go test ./...
+        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
+          echo "Some files are not properly formatted"
+          exit 1
+        fi
+        goVetResult=$(go vet ./...)
+        if [ $(echo ${#goVetResult}) != 0 ]; then
+            echo -e "go vet errors \n$goVetResult"
+            exit 1
+        fi
 
     - name: Setup gcloud
       uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
@@ -60,14 +52,14 @@ jobs:
         project_id: sap-se-cx-gopher
         export_default_credentials: true
 
-   # - name: Build Image
-   #   run: |
-   #     docker build -t eu.gcr.io/$PROJECT_ID/binding:PR-$PR_NUMBER .
+    - name: Build Image
+      run: |
+        docker build -t eu.gcr.io/$PROJECT_ID/binding:PR-$PR_NUMBER .
 
-#    - name: Push Image
-#      run: |
-#        gcloud auth configure-docker -q
-#        docker push eu.gcr.io/$PROJECT_ID/binding:PR-$PR_NUMBER#
+    - name: Push Image
+      run: |
+        gcloud auth configure-docker -q
+        docker push eu.gcr.io/$PROJECT_ID/binding:PR-$PR_NUMBER#
 
     - name: Prepare k3s and helm 3
       run: |
@@ -76,15 +68,15 @@ jobs:
         curl -s https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
         while [[ $(kubectl get nodes -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "Waiting for cluster nodes to be ready"; sleep 2; done
 
-#    - name: Install Bindings component using Helm
-#      run: |
-#        helm install binding ./charts/binding --set images.bindingController.version="PR-${PR_NUMBER}" --wait
+    - name: Install Bindings component using Helm
+      run: |
+        helm install binding ./charts/binding --set images.bindingController.version="PR-${PR_NUMBER}" --wait
 
-#    - name: Apply test scenario and check if secrets are injected
-#      run: |
- #       ./scripts/create-scenario.sh
-#        while [[ $(kubectl get po -l app=sandbox -ojson | jq '.items | .[] | .spec.containers') != *"TEST_PASSWORD"* ]]; do echo "Waiting for the secrets to inject"; sleep 2; done
-#        kubectl get po -l app=sandbox -ojson | jq '.items | .[] | .spec.containers'
+    - name: Apply test scenario and check if secrets are injected
+      run: |
+        ./scripts/create-scenario.sh
+        while [[ $(kubectl get po -l app=sandbox -ojson | jq '.items | .[] | .spec.containers') != *"TEST_PASSWORD"* ]]; do echo "Waiting for the secrets to inject"; sleep 2; done
+        kubectl get po -l app=sandbox -ojson | jq '.items | .[] | .spec.containers'
 
 
     # Update check run 
